### ISSUE TITLE
error when upload to lamda

### ISSUE THREAD

**Issue by JGamboa** [mnapoli/bref-laravel-demo#2]
i did download and upload to lambda aws, but it gives me {"message": "Internal server error"}

**Comment by mnapoli** [comment]
Hi, run `bref logs` to read the logs of your application (or go on AWS CloudWatch in your AWS console).

**Comment by JGamboa** [comment]
already did that and i dont understand what is the problem.

19:44:58
START RequestId: c9db350e-c744-11e8-a867-d3ad835010fa Version: $LATEST
START RequestId: c9db350e-c744-11e8-a867-d3ad835010fa Version: $LATEST

19:44:58
2018-10-03T19:44:58.635Z c9db350e-c744-11e8-a867-d3ad835010fa Error: spawn EACCES at exports._errnoException (util.js:1018:11) at ChildProcess.spawn (internal/child_process.js:319:11) at exports.spawn (child_process.js:378:9) at exports.handle (/var/task/handler.js:39:18)

19:44:58
END RequestId: c9db350e-c744-11e8-a867-d3ad835010fa

19:44:58
REPORT RequestId: c9db350e-c744-11e8-a867-d3ad835010fa Duration: 53.08 ms Billed Duration: 100 ms Memory Size: 1024 MB Max Memory Used: 20 MB

19:44:58
RequestId: c9db350e-c744-11e8-a867-d3ad835010fa Process exited before completing request

19:45:01
START RequestId: d147d7bf-c744-11e8-8f3c-21d55bdb0e42 Version: $LATEST

19:45:01
2018-10-03T19:45:01.795Z d147d7bf-c744-11e8-8f3c-21d55bdb0e42 Error: spawn EACCES at exports._errnoException (util.js:1018:11) at ChildProcess.spawn (internal/child_process.js:319:11) at exports.spawn (child_process.js:378:9) at exports.handle (/var/task/handler.js:39:18)

19:45:01
END RequestId: d147d7bf-c744-11e8-8f3c-21d55bdb0e42

19:45:01
REPORT RequestId: d147d7bf-c744-11e8-8f3c-21d55bdb0e42 Duration: 53.68 ms Billed Duration: 100 ms Memory Size: 1024 MB Max Memory Used: 20 MB

19:45:01
RequestId: d147d7bf-c744-11e8-8f3c-21d55bdb0e42 Process exited before completing request

19:45:04
START RequestId: d2ccf0de-c744-11e8-96d9-afdccf63ade4 Version: $LATEST

19:45:04
2018-10-03T19:45:04.337Z d2ccf0de-c744-11e8-96d9-afdccf63ade4 Error: spawn EACCES at exports._errnoException (util.js:1018:11) at ChildProcess.spawn (internal/child_process.js:319:11) at exports.spawn (child_process.js:378:9) at exports.handle (/var/task/handler.js:39:18)

19:45:04
END RequestId: d2ccf0de-c744-11e8-96d9-afdccf63ade4

19:45:04
REPORT RequestId: d2ccf0de-c744-11e8-96d9-afdccf63ade4 Duration: 42.89 ms Billed Duration: 100 ms Memory Size: 1024 MB Max Memory Used: 20 MB

19:45:04
RequestId: d2ccf0de-c744-11e8-96d9-afdccf63ade4 Process exited before completing request

19:45:06
START RequestId: d4449d05-c744-11e8-9bad-d59bf1aae880 Version: $LATEST

19:45:06
2018-10-03T19:45:06.797Z d4449d05-c744-11e8-9bad-d59bf1aae880 Error: spawn EACCES at exports._errnoException (util.js:1018:11) at ChildProcess.spawn (internal/child_process.js:319:11) at exports.spawn (child_process.js:378:9) at exports.handle (/var/task/handler.js:39:18)

19:45:06
END RequestId: d4449d05-c744-11e8-9bad-d59bf1aae880

19:45:06
REPORT RequestId: d4449d05-c744-11e8-9bad-d59bf1aae880 Duration: 58.59 ms Billed Duration: 100 ms Memory Size: 1024 MB Max Memory Used: 20 MB

19:45:06
RequestId: d4449d05-c744-11e8-9bad-d59bf1aae880 Process exited before completing request

19:45:08
START RequestId: d5384bf7-c744-11e8-8ff8-975ec7e491d2 Version: $LATEST

19:45:08
2018-10-03T19:45:08.400Z d5384bf7-c744-11e8-8ff8-975ec7e491d2 Error: spawn EACCES at exports._errnoException (util.js:1018:11) at ChildProcess.spawn (internal/child_process.js:319:11) at exports.spawn (child_process.js:378:9) at exports.handle (/var/task/handler.js:39:18)

19:45:08
END RequestId: d5384bf7-c744-11e8-8ff8-975ec7e491d2

19:45:08
REPORT RequestId: d5384bf7-c744-11e8-8ff8-975ec7e491d2 Duration: 43.64 ms Billed Duration: 100 ms Memory Size: 1024 MB Max Memory Used: 20 MB

19:45:08
RequestId: d5384bf7-c744-11e8-8ff8-975ec7e491d2 Process exited before completing request

19:46:34
START RequestId: 085243dc-c745-11e8-b04c-e17613370c77 Version: $LATEST

19:46:34
2018-10-03T19:46:34.173Z 085243dc-c745-11e8-b04c-e17613370c77 Error: spawn EACCES at exports._errnoException (util.js:1018:11) at ChildProcess.spawn (internal/child_process.js:319:11) at exports.spawn (child_process.js:378:9) at exports.handle (/var/task/handler.js:39:18)

19:46:34
END RequestId: 085243dc-c745-11e8-b04c-e17613370c77

19:46:34
REPORT RequestId: 085243dc-c745-11e8-b04c-e17613370c77 Duration: 67.05 ms Billed Duration: 100 ms Memory Size: 1024 MB Max Memory Used: 20 MB

19:46:34
RequestId: 085243dc-c745-11e8-b04c-e17613370c77 Process exited before completing request

19:47:50
START RequestId: 360d6ba3-c745-11e8-90bb-ff81761c60fd Version: $LATEST

19:47:50
2018-10-03T19:47:50.881Z 360d6ba3-c745-11e8-90bb-ff81761c60fd Error: spawn EACCES at exports._errnoException (util.js:1018:11) at ChildProcess.spawn (internal/child_process.js:319:11) at exports.spawn (child_process.js:378:9) at exports.handle (/var/task/handler.js:39:18)

19:47:50
END RequestId: 360d6ba3-c745-11e8-90bb-ff81761c60fd

19:47:50
REPORT RequestId: 360d6ba3-c745-11e8-90bb-ff81761c60fd Duration: 69.00 ms Billed Duration: 100 ms Memory Size: 1024 MB Max Memory Used: 20 MB

19:47:50
RequestId: 360d6ba3-c745-11e8-90bb-ff81761c60fd Process exited before completing request

19:49:47
START RequestId: 7bcdb6c3-c745-11e8-ad74-cd275e166107 Version: $LATEST

19:49:47
2018-10-03T19:49:47.912Z 7bcdb6c3-c745-11e8-ad74-cd275e166107 Error: spawn EACCES at exports._errnoException (util.js:1018:11) at ChildProcess.spawn (internal/child_process.js:319:11) at exports.spawn (child_process.js:378:9) at exports.handle (/var/task/handler.js:39:18)

19:49:47
END RequestId: 7bcdb6c3-c745-11e8-ad74-cd275e166107

19:49:47
REPORT RequestId: 7bcdb6c3-c745-11e8-ad74-cd275e166107 Duration: 74.32 ms Billed Duration: 100 ms Memory Size: 1024 MB Max Memory Used: 20 MB

19:49:47
RequestId: 7bcdb6c3-c745-11e8-ad74-cd275e166107 Process exited before completing request

20:03:01
START RequestId: 5491d967-c747-11e8-9962-05063cf73690 Version: $LATEST

20:03:01
2018-10-03T20:03:01.081Z 5491d967-c747-11e8-9962-05063cf73690 Error: spawn EACCES at exports._errnoException (util.js:1018:11) at ChildProcess.spawn (internal/child_process.js:319:11) at exports.spawn (child_process.js:378:9) at exports.handle (/var/task/handler.js:39:18)

20:03:01
END RequestId: 5491d967-c747-11e8-9962-05063cf73690

20:03:01
REPORT RequestId: 5491d967-c747-11e8-9962-05063cf73690 Duration: 71.44 ms Billed Duration: 100 ms Memory Size: 1024 MB Max Memory Used: 20 MB

20:03:01
RequestId: 5491d967-c747-11e8-9962-05063cf73690 Process exited before completing request

20:04:01
START RequestId: 78702177-c747-11e8-a75d-e9f85fdc2891 Version: $LATEST

20:04:01
2018-10-03T20:04:01.242Z 78702177-c747-11e8-a75d-e9f85fdc2891 Error: spawn EACCES at exports._errnoException (util.js:1018:11) at ChildProcess.spawn (internal/child_process.js:319:11) at exports.spawn (child_process.js:378:9) at exports.handle (/var/task/handler.js:39:18)

20:04:01
END RequestId: 78702177-c747-11e8-a75d-e9f85fdc2891

20:04:01
REPORT RequestId: 78702177-c747-11e8-a75d-e9f85fdc2891 Duration: 58.06 ms Billed Duration: 100 ms Memory Size: 1024 MB Max Memory Used: 20 MB

20:04:01
RequestId: 78702177-c747-11e8-a75d-e9f85fdc2891 Process exited before completing request

20:04:37
START RequestId: 8e4370b1-c747-11e8-9f68-756bc203e6bd Version: $LATEST

20:04:37
2018-10-03T20:04:37.839Z 8e4370b1-c747-11e8-9f68-756bc203e6bd Error: spawn EACCES at exports._errnoException (util.js:1018:11) at ChildProcess.spawn (internal/child_process.js:319:11) at exports.spawn (child_process.js:378:9) at exports.handle (/var/task/handler.js:39:18)

20:04:37
END RequestId: 8e4370b1-c747-11e8-9f68-756bc203e6bd

20:04:37
REPORT RequestId: 8e4370b1-c747-11e8-9f68-756bc203e6bd Duration: 45.41 ms Billed Duration: 100 ms Memory Size: 1024 MB Max Memory Used: 20 MB

20:04:37
RequestId: 8e4370b1-c747-11e8-9f68-756bc203e6bd Process exited before completing request

20:06:00
START RequestId: bfd36e48-c747-11e8-a867-d3ad835010fa Version: $LATEST

20:06:01
2018-10-03T20:06:01.013Z bfd36e48-c747-11e8-a867-d3ad835010fa Error: spawn EACCES at exports._errnoException (util.js:1018:11) at ChildProcess.spawn (internal/child_process.js:319:11) at exports.spawn (child_process.js:378:9) at exports.handle (/var/task/handler.js:39:18)

20:06:01
END RequestId: bfd36e48-c747-11e8-a867-d3ad835010fa

20:06:01
REPORT RequestId: bfd36e48-c747-11e8-a867-d3ad835010fa Duration: 54.64 ms Billed Duration: 100 ms Memory Size: 1024 MB Max Memory Used: 20 MB

20:06:01
RequestId: bfd36e48-c747-11e8-a867-d3ad835010fa Process exited before completing request

**Comment by mnapoli** [comment]
Mhh that is weird indeed, did you deploy with `vendor/bin/bref deploy` and *not* `serverless deploy`?

Could you try removing the `.bref` directory and try `bref deploy` again?

**Comment by JGamboa** [comment]
yes i did use "vendor/bin/bref deploy" , i bought a domain to do test.
Already try deleting .bref, i deleted the envirment like 3 times to test :/
I have an application on laravel that i would really like to have on lambda, im i been trying since yesterday with this :D. And ty for your bref its looks really cool :D

**Comment by mnapoli** [comment]
OK that's too bad indeed 🤔 

Last thing to try maybe: run `composer update` so that you get the latest Bref version. I see that there is the `composer.lock` committed in this repository so maybe it's on an old (incompatible) version…

**Comment by JGamboa** [comment]
Already try that, didnt work :D

**Comment by JGamboa** [comment]
Really dont know what to do, i have been trying the last 24 hours with diferent project and no luck with any of them

**Comment by mnapoli** [comment]
I've given it a try again and I was able to redeploy the project successfully, even after updating Composer (https://k6ay4xiyld.execute-api.eu-west-3.amazonaws.com/dev)

I have a `.env` file (nothing specific in there), have you created it? (`APP_KEY` is not empty for me)

**Comment by JGamboa** [comment]
i will try one more time i will download and update again :D i will reach you in a few min

**Comment by JGamboa** [comment]
It work, now in a new project the composer stay ^0.2.27 even when y made a cmposer update, but in this example is ~0.2.7

**Comment by JGamboa** [comment]
Now it seems it work :D , the problem with composer require its that the version that match doenst work, but if i change manuale to the version of this example works fine

**Comment by JGamboa** [comment]
Do you have a tip to connect this with a mysql rds ? i put the mysql data but it doenst connect

**Comment by mnapoli** [comment]
OK great I'll close this and update the requirements in `composer.json`.

I want to write a guide for RDS, there is none yet. It's especially hard with VPC, so for testing I recommend not using VPC first.

**Comment by JGamboa** [comment]
Hi, i already done the all RDS theme a few mins after i made this work.
With the VPC is to give lambda access to the vpc and subnet of the RDS, then attach a VPC Lambda execution policies and its work like a charm!.
I just encounter one problem, i have every GET resource working OK, but the POST resource arent working,and iin the logs i dont have any error.
